apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend-dev
data:
  DATABASE_HOST: "mysql.database-dev.svc.cluster.local"
  DATABASE_NAME: "loungegario"
  NODE_ENV: "development" 