apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: loungegario/frontend:dev
        workingDir: /app
        command: ["/bin/sh", "-c"]
        args: ["node server.js"]
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - configMapRef:
            name: frontend-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /_next/static/development/_buildManifest.js
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /_next/static/development/_buildManifest.js
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20 