apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: database-dev
data:
  my.cnf: |
    [mysqld]
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    default-authentication-plugin = mysql_native_password
    skip-character-set-client-handshake
    init-connect = 'SET NAMES utf8mb4' 