apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend
data:
  NEXT_PUBLIC_API_URL: "http://backend.backend.svc.cluster.local:8080"
  NODE_ENV: "production"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  NEXT_PUBLIC_BASE_URL: "http://34.39.140.137"
  NEXT_PUBLIC_APP_URL: "http://34.39.140.137"
