apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: frontend 
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: mydb
  MYSQL_USER: user
  MYSQL_PASSWORD: user
