name: Deploy Frontend and Backend to GKE

on:
  push:
    branches: [ master, release, dev ]

env:
  GKE_CLUSTER: cluster
  GKE_ZONE: southamerica-east1
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

  DOCKER_USER: loungegario
  FRONT_IMAGE: loungegario/frontend:${{ github.ref_name }}
  BACK_IMAGE: loungegario/backend:${{ github.ref_name }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
      k8s: ${{ steps.filter.outputs.k8s }}
    steps:
      - uses: actions/checkout@v3

      - name: Check file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
            k8s:
              - 'k8s/**'

  build-and-deploy:
    needs: changes
    runs-on: ubuntu-latest
    if: needs.changes.outputs.frontend == 'true' || needs.changes.outputs.backend == 'true' || needs.changes.outputs.k8s == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build and Push Frontend
        if: needs.changes.outputs.frontend == 'true'
        run: |
          docker build -t $FRONT_IMAGE ./frontend
          docker push $FRONT_IMAGE

      - name: Build and Push Backend
        if: needs.changes.outputs.backend == 'true'
        run: |
          docker build -t $BACK_IMAGE ./backend
          docker push $BACK_IMAGE

      # BLOCO DE DEPLOY — somente se branch for release ou master
      - name: Authenticate to Google Cloud
        if: github.ref_name == 'master' || github.ref_name == 'release'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        if: github.ref_name == 'master' || github.ref_name == 'release'
        uses: google-github-actions/setup-gcloud@v1

      - name: Install GKE gcloud auth plugin
        if: github.ref_name == 'master' || github.ref_name == 'release'
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Get GKE Credentials
        if: github.ref_name == 'master' || github.ref_name == 'release'
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

      - name: Update frontend deployment
        if: (needs.changes.outputs.frontend == 'true') && (github.ref_name == 'master' || github.ref_name == 'release')
        run: |
          kubectl set image deployment/frontend frontend=$FRONT_IMAGE -n frontend
          kubectl rollout restart deployment/frontend -n frontend

      - name: Update backend deployment
        if: (needs.changes.outputs.backend == 'true') && (github.ref_name == 'master' || github.ref_name == 'release')
        run: |
          kubectl set image deployment/backend backend=$BACK_IMAGE -n backend
          kubectl rollout restart deployment/backend -n backend

      - name: Apply Kubernetes manifests
        if: (needs.changes.outputs.k8s == 'true') && (github.ref_name == 'master' || github.ref_name == 'release')
        run: |
          kubectl apply -f k8s/
