name: Deploy to GKE

on:
  push:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: cluster
  GKE_ZONE: southamerica-east1-a
  DEPLOYMENT_NAME: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Push Frontend
      run: |
        docker build -t gcr.io/$PROJECT_ID/frontend:${{ github.sha }} ./frontend
        docker push gcr.io/$PROJECT_ID/frontend:${{ github.sha }}

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE
        kubectl set image deployment/$DEPLOYMENT_NAME frontend=gcr.io/$PROJECT_ID/frontend:${{ github.sha }}
